# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d673fa239c2fdfc7ea6cc5aff64e5084ae594ee5cae155f4a85b3d2ae62a7ef03416a3ff8dac9dadc147417605ce185a7c97c1b33eafeacece6f3449b545675

test:
  secret_key_base: 35775905901fd20dc17b7a6fdfa967b1afa810062e3a780a4ff904d17cc37892c908cb6f606dcaf06aa92f4f331c26fd0252d1f941447fd4e3f419c7b9cf8bec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
